server {
    listen 80;
    listen [::]:80;
    server_name stage0.gbadedata.com;
    return 301 https://$host$request_uri;
}

server {
    server_name stage0.gbadedata.com;

    root /var/www/stage0;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location = /api {
        default_type application/json;
        return 200 '{"message":"HNGI14 Stage 0","track":"DevOps","username":"OJ"}';
    }

    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/stage0.gbadedata.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/stage0.gbadedata.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}